<?php

/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
?>
<div class="jumbotron">
    <h1>Cadastro de Corretores</h1>
    <p><a href="<?= $this->url('cadastros', [
                    'controller' => 'corretor',
                    'action' => 'editar'
                ]) ?>">Novo corretor</a></p>
    <table>
        <thead>
            <tr>
                <th>Matrícula</th>
                <th>Nome</th>
            </tr>
        </thead>
        <tbody>
            <?= $this->partialLoop('corretores.phtml', $this->corretores) ?>
        </tbody>
    </table>
    <p>
        <a href="<?= $this->url('cadastros') ?>">Voltar</a>
</div>